### ISSUE TITLE
build instruction

### ISSUE THREAD

**Issue by fredmo** [retiredtab/LineageOS-build-manifests#1]
Based on your comment 

>     Q1. Where are the source and kernel source files?
    A1. The kernel source files are at
    https://github.com/syphyr/android_kernel_samsung_msm8976/tree/lineage-16.0

    The device tree files are at
    https://github.com/retiredtab/msm8976-common/tree/lineage-20
    https://github.com/retiredtab/gts210vewifi/tree/lineage-20

    The vendor tree files are at
    https://github.com/retiredtab/proprietary_vendor_samsung_msm8976
    
    The manifest.xml (or roomservice.xml) and build instructions for LineageOS 20 are at
    https://github.com/retiredtab/LineageOS-build-manifests/tree/main/20/msm8976

I tried to adapt following : 
https://github.com/retiredtab/LineageOS-build-manifests/blob/main/20/msm8976/20-msm8976-build-instructions.txt

```
#!/bin/bash
set -x

#NB_CPU=$(nproc --all)
NB_CPU=1
# Step 1: Install necessary packages
#sudo apt-get update
#sudo apt install -y git-core gnupg flex bison gperf build-essential \
# zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
# lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
# libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

# Step 2: Set up the repo tool
#mkdir -p ~/bin
#PATH=~/bin:$PATH
#curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo
#chmod a+x /usr/bin/repo

# Step 3: Create a directory for the source
mkdir -p ~/android
cd ~/android

# Step 4: Initialize the repo
repo init -u https://github.com/LineageOS-UL/android.git -b lineage-20.0 --git-lfs

# Step 6: Download the local manifest for your device
mkdir -p .repo/local_manifests
wget https://github.com/retiredtab/LineageOS-build-manifests/raw/main/20/msm8976/msm8976-20.xml -O .repo/local_manifests/msm8976-20.xml



# Step 5: Download the source code
repo sync -c -j$NB_CPU --force-sync --no-clone-bundle --no-tags



# git revert Remove libbfqio
cd vendor/lineage
git revert --no-edit 8f67d055b36d992f2f09aa6f733aa06ee3d5b917
cd ../..

# 6. # Patch to make newpipe show video

wget https://github.com/retiredtab/LineageOS-build-manifests/raw/main/20/msm8976/alloc_controller-ionHeapId.diff -O /tmp/alloc_controller-ionHeapId.diff
cd hardware/qcom-caf/msm8952/display
patch -p1 < /tmp/alloc_controller-ionHeapId.diff
cd ../../../..

# 7. # Patch to fix wifi compiler error

wget https://github.com/retiredtab/LineageOS-build-manifests/raw/main/20/msm8976/driver_cmd_nl80211_patch.diff -O /tmp/driver_cmd_nl80211_patch.diff
cd hardware/qcom-caf/wlan
patch -p1 < /tmp/driver_cmd_nl80211_patch.diff
cd ../../..

# 8. # Multiple patches for kernel to make it work with LineageOS 20

wget https://github.com/retiredtab/LineageOS-build-manifests/raw/main/20/msm8976/msm8976-kernel-april-15.diff -O /tmp/msm8976-kernel-april-15.diff
cd kernel/samsung/msm8976
patch -p1 < /tmp/msm8976-kernel-april-15.diff
cd ../../..


# Step 8: Set up the build environment
source build/envsetup.sh


# Step 9: Choose your device
breakfast gts210vewifi

# I did also, adb connect and  : cd ~/android/device/samsung/gts210vewifi ; ./extract-files.sh
# but it is still missing : out/target/product/gts210vewifi/obj/PACKAGING/target_files_intermediates/lineage_gts210vewifi-target_files-eng.me/SYSTEM/vendor/vendor/etc/recovery.img'

brunch gts210vewifi

``` 

On the 17/05/24 on Ubuntu 24.04, it s failing on  : 

Traceback (most recent call last):
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/__main__.py", line 12, in <module>
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/make_recovery_patch.py", line 73, in <module>
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/make_recovery_patch.py", line 69, in main
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/common.py", line 3603, in MakeRecoveryPatch
  File "/home/me/android/out/host/linux-x86/bin/make_recovery_patch/make_recovery_patch.py", line 65, in output_sink
FileNotFoundError: [Errno 2] No such file or directory: 'out/target/product/gts210vewifi/obj/PACKAGING/target_files_intermediates/lineage_gts210vewifi-target_files-eng.me/SYSTEM/vendor/vendor/etc/recovery.img'

but, the file is present in another folder : 
cd /home/me/android/
find . -name recovery.img
./out/target/product/gts210vewifi/recovery.img
./out/target/product/gts210vewifi/obj/PACKAGING/target_files_intermediates/lineage_gts210vewifi-target_files-eng.me/BOOTABLE_IMAGES/recovery.img

**Comment by xc112lg** [comment]
were you able to fix this?

**Comment by fredmo** [comment]
not yet

**Comment by fredmo** [comment]
based on https://xdaforums.com/t/lineageos-19-1-for-sm-t580-gtaxlwifi-sm-t585-gtaxllte-sm-p580-gtanotexlwifi-and-sm-p585-gtanotexllte.4432957/post-89525959 :

![image](https://github.com/retiredtab/LineageOS-build-manifests/assets/3090107/0ab34943-e0c8-42f8-9e79-eb29515ab0f3)

After the cherry pick / resolve / merge , the zip file is generated.

@retiredtab  , the commit on the branch lineageos20 is available on this fork : https://github.com/fredmo/android_build/commit/fff9c89f9bc5c84a7eb0f0eeb29680d01efe98b4

This ticket can be closed, 
( I haven't tested yet the flashing of this generated image )
